development:
  adapter: postgresql
  encoding: unicode
  database: project_test_development
  pool: 5
  username: DarthNeel
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: project_test_development
  pool: 5
  username: DarthNeel
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: project_test_development
  pool: 5
  username: DarthNeel
  password:
  host: localhost